""" removed chatb shit 

Revision ID: 726e9b7cd96b
Revises: 95fc6afe0e48
Create Date: 2024-04-13 22:10:45.326541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726e9b7cd96b'
down_revision = '95fc6afe0e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('chatbimg')
        batch_op.drop_column('chatbname')
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.VARCHAR(length=2000), nullable=False))
        batch_op.add_column(sa.Column('chatbname', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('chatbimg', sa.VARCHAR(length=250), nullable=True))

    # ### end Alembic commands ###
