"""Initial Migration

Revision ID: 95fc6afe0e48
Revises: 
Create Date: 2024-04-13 21:55:49.065817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fc6afe0e48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=500), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('chatbname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('prompt',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.drop_column('chatbbio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbbio', sa.VARCHAR(length=1000), nullable=True))
        batch_op.alter_column('prompt',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
        batch_op.alter_column('chatbname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
